tasks:
  - command: cd helloworld && ./gradlew build
  - command: cd ../SBAserver && ./gradlew build

# Ports to expose on workspace startup (optional)
# ports:
#   - port: 8081
#     onOpen: open-preview